DROP SCHEMA PUBLIC CASCADE;

DROP TABLE Follower IF EXISTS;
DROP TABLE Post IF EXISTS;
DROP TABLE "User" IF EXISTS;

CREATE TABLE Follower (userId integer NOT NULL, followsUserId integer NOT NULL, PRIMARY KEY (userId, followsUserId));
CREATE TABLE Post (id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), authorId integer NOT NULL, content varchar(4000), isPublic bit, PRIMARY KEY (id));
CREATE TABLE "User" (id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), login varchar(200), email varchar(200), password varchar(100), firstName varchar(200), lastName varchar(200), gender char(1), dob date, statusId char(1) ,PRIMARY KEY (id));
ALTER TABLE Follower ADD CONSTRAINT FKFollower761503 FOREIGN KEY (followsUserId) REFERENCES "User" (id);
ALTER TABLE Follower ADD CONSTRAINT FKFollower936392 FOREIGN KEY (userId) REFERENCES "User" (id);
ALTER TABLE Post ADD CONSTRAINT author FOREIGN KEY (authorId) REFERENCES "User" (id);


