DROP SCHEMA PUBLIC CASCADE;

DROP TABLE Follower
IF EXISTS;
DROP TABLE Post
IF EXISTS;
DROP TABLE "User"
IF EXISTS;

CREATE TABLE Follower
(
    userId integer NOT NULL,
    followsUserId integer NOT NULL,
    PRIMARY KEY (userId, followsUserId)
);
CREATE TABLE Post (id integer GENERATED BY DEFAULT AS IDENTITY
(START
WITH 1), authorId integer NOT NULL, content varchar
(4000) NOT NULL, isPublic bit, PRIMARY KEY
(id), comments varchar
(200) Array, tags varchar
(200) Array);
CREATE TABLE "User" (id integer GENERATED BY DEFAULT AS IDENTITY
(START
WITH 1), login varchar
(200) NOT NULL, email varchar
(200) NOT NULL, password varchar
(100) NOT NULL, firstName varchar
(200) NOT NULL, lastName varchar
(200) NOT NULL, gender char
(1), dob date, statusId char
(1),PRIMARY KEY
(id), likedPosts int Array, amountOfFollowee int, amountOfFollowers int);
ALTER TABLE Follower ADD CONSTRAINT FKFollower761503 FOREIGN KEY (followsUserId) REFERENCES "User" (id) on delete cascade;
ALTER TABLE Follower ADD CONSTRAINT FKFollower936392 FOREIGN KEY (userId) REFERENCES "User" (id) on delete cascade;
ALTER TABLE Post ADD CONSTRAINT author FOREIGN KEY (authorId) REFERENCES "User" (id) on delete cascade;
ALTER TABLE "User" ADD CONSTRAINT user_unique_login UNIQUE (login);
ALTER TABLE "User" ADD CONSTRAINT user_unique_email UNIQUE (email);
ALTER TABLE "User" ADD CONSTRAINT user_check_login_blank CHECK (TRIM(login) <>'');
ALTER TABLE "User" ADD CONSTRAINT user_check_firstName_blank CHECK (TRIM(firstName) <>'');
ALTER TABLE "User" ADD CONSTRAINT user_check_lastName_blank CHECK (TRIM(lastName) <>'');
ALTER TABLE "User" ADD CONSTRAINT user_check_email_blank CHECK (TRIM(email) <>'');
ALTER TABLE "User" ADD CONSTRAINT user_check_password_blank CHECK (TRIM(password) <>'');
ALTER TABLE "User" ADD CONSTRAINT user_check_gender CHECK (gender in ('M','F'));
ALTER TABLE "User" ADD CONSTRAINT user_check_status CHECK (statusId in ('I','A', 'O', 'B'));
ALTER TABLE Post ADD CONSTRAINT post_check_content_blank CHECK (TRIM(content) <>'');
